/* tslint:disable */
/* eslint-disable */
/**
 * blog/blog.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BlogBlog } from './BlogBlog';
import {
    BlogBlogFromJSON,
    BlogBlogFromJSONTyped,
    BlogBlogToJSON,
} from './BlogBlog';

/**
 * 
 * @export
 * @interface BlogblogGetResponse
 */
export interface BlogblogGetResponse {
    /**
     * 
     * @type {BlogBlog}
     * @memberof BlogblogGetResponse
     */
    blog?: BlogBlog;
}

/**
 * Check if a given object implements the BlogblogGetResponse interface.
 */
export function instanceOfBlogblogGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BlogblogGetResponseFromJSON(json: any): BlogblogGetResponse {
    return BlogblogGetResponseFromJSONTyped(json, false);
}

export function BlogblogGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogblogGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blog': !exists(json, 'blog') ? undefined : BlogBlogFromJSON(json['blog']),
    };
}

export function BlogblogGetResponseToJSON(value?: BlogblogGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blog': BlogBlogToJSON(value.blog),
    };
}

