/* tslint:disable */
/* eslint-disable */
/**
 * lottery/lottery.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LotteryLotteryQuery
 */
export interface LotteryLotteryQuery {
    /**
     * 
     * @type {Array<number>}
     * @memberof LotteryLotteryQuery
     */
    ids?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof LotteryLotteryQuery
     */
    userId?: string;
}

/**
 * Check if a given object implements the LotteryLotteryQuery interface.
 */
export function instanceOfLotteryLotteryQuery(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LotteryLotteryQueryFromJSON(json: any): LotteryLotteryQuery {
    return LotteryLotteryQueryFromJSONTyped(json, false);
}

export function LotteryLotteryQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): LotteryLotteryQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ids': !exists(json, 'ids') ? undefined : json['ids'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
    };
}

export function LotteryLotteryQueryToJSON(value?: LotteryLotteryQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ids': value.ids,
        'userId': value.userId,
    };
}

