
before_script:
  - docker info
build:
  stage: build
  script:
    - echo "$ENV_VAR" > "apps/frontend/.env"
    - docker build -t mozyy/empty-compose-frontend:latest --target frontend-runner -f Dockerfile/Dockerfile .
