/* tslint:disable */
/* eslint-disable */
/**
 * oauth/oauth.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthNewClient
 */
export interface OauthNewClient {
    /**
     * 
     * @type {string}
     * @memberof OauthNewClient
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthNewClient
     */
    redirectUri?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthNewClient
     */
    defaultScope?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthNewClient
     */
    passdata?: string;
}

/**
 * Check if a given object implements the OauthNewClient interface.
 */
export function instanceOfOauthNewClient(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OauthNewClientFromJSON(json: any): OauthNewClient {
    return OauthNewClientFromJSONTyped(json, false);
}

export function OauthNewClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthNewClient {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'redirectUri': !exists(json, 'redirectUri') ? undefined : json['redirectUri'],
        'defaultScope': !exists(json, 'defaultScope') ? undefined : json['defaultScope'],
        'passdata': !exists(json, 'passdata') ? undefined : json['passdata'],
    };
}

export function OauthNewClientToJSON(value?: OauthNewClient | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'redirectUri': value.redirectUri,
        'defaultScope': value.defaultScope,
        'passdata': value.passdata,
    };
}

