/* tslint:disable */
/* eslint-disable */
/**
 * oauth/oauth.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthResourceResponse
 */
export interface OauthResourceResponse {
    /**
     * 
     * @type {string}
     * @memberof OauthResourceResponse
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthResourceResponse
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthResourceResponse
     */
    scope?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthResourceResponse
     */
    redirectUri?: string;
    /**
     * 
     * @type {Date}
     * @memberof OauthResourceResponse
     */
    until?: Date;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof OauthResourceResponse
     */
    extensions?: { [key: string]: string; };
}

/**
 * Check if a given object implements the OauthResourceResponse interface.
 */
export function instanceOfOauthResourceResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OauthResourceResponseFromJSON(json: any): OauthResourceResponse {
    return OauthResourceResponseFromJSONTyped(json, false);
}

export function OauthResourceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthResourceResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'clientId': !exists(json, 'clientId') ? undefined : json['clientId'],
        'scope': !exists(json, 'scope') ? undefined : json['scope'],
        'redirectUri': !exists(json, 'redirectUri') ? undefined : json['redirectUri'],
        'until': !exists(json, 'until') ? undefined : (new Date(json['until'])),
        'extensions': !exists(json, 'extensions') ? undefined : json['extensions'],
    };
}

export function OauthResourceResponseToJSON(value?: OauthResourceResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ownerId': value.ownerId,
        'clientId': value.clientId,
        'scope': value.scope,
        'redirectUri': value.redirectUri,
        'until': value.until === undefined ? undefined : (value.until.toISOString()),
        'extensions': value.extensions,
    };
}

