/* tslint:disable */
/* eslint-disable */
/**
 * oauth/oauth.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthPattern
 */
export interface OauthPattern {
    /**
     * 
     * @type {string}
     * @memberof OauthPattern
     */
    equal?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthPattern
     */
    prefix?: string;
    /**
     * 
     * @type {string}
     * @memberof OauthPattern
     */
    regex?: string;
}

/**
 * Check if a given object implements the OauthPattern interface.
 */
export function instanceOfOauthPattern(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OauthPatternFromJSON(json: any): OauthPattern {
    return OauthPatternFromJSONTyped(json, false);
}

export function OauthPatternFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthPattern {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'equal': !exists(json, 'equal') ? undefined : json['equal'],
        'prefix': !exists(json, 'prefix') ? undefined : json['prefix'],
        'regex': !exists(json, 'regex') ? undefined : json['regex'],
    };
}

export function OauthPatternToJSON(value?: OauthPattern | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'equal': value.equal,
        'prefix': value.prefix,
        'regex': value.regex,
    };
}

