/* tslint:disable */
/* eslint-disable */
/**
 * oauth/oauth.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OauthPattern } from './OauthPattern';
import {
    OauthPatternFromJSON,
    OauthPatternFromJSONTyped,
    OauthPatternToJSON,
} from './OauthPattern';

/**
 * 
 * @export
 * @interface OauthConfig
 */
export interface OauthConfig {
    /**
     * 
     * @type {number}
     * @memberof OauthConfig
     */
    id?: number;
    /**
     * 
     * @type {OauthPattern}
     * @memberof OauthConfig
     */
    pattern?: OauthPattern;
    /**
     * 
     * @type {string}
     * @memberof OauthConfig
     */
    scope?: string;
}

/**
 * Check if a given object implements the OauthConfig interface.
 */
export function instanceOfOauthConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OauthConfigFromJSON(json: any): OauthConfig {
    return OauthConfigFromJSONTyped(json, false);
}

export function OauthConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'pattern': !exists(json, 'pattern') ? undefined : OauthPatternFromJSON(json['pattern']),
        'scope': !exists(json, 'scope') ? undefined : json['scope'],
    };
}

export function OauthConfigToJSON(value?: OauthConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'pattern': OauthPatternToJSON(value.pattern),
        'scope': value.scope,
    };
}

