/* tslint:disable */
/* eslint-disable */
/**
 * oauth/oauth.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthAuthorizeResponse
 */
export interface OauthAuthorizeResponse {
    /**
     * 
     * @type {string}
     * @memberof OauthAuthorizeResponse
     */
    code?: string;
}

/**
 * Check if a given object implements the OauthAuthorizeResponse interface.
 */
export function instanceOfOauthAuthorizeResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OauthAuthorizeResponseFromJSON(json: any): OauthAuthorizeResponse {
    return OauthAuthorizeResponseFromJSONTyped(json, false);
}

export function OauthAuthorizeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthAuthorizeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
    };
}

export function OauthAuthorizeResponseToJSON(value?: OauthAuthorizeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
    };
}

