/* tslint:disable */
/* eslint-disable */
/**
 * oss/oss.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OssBucketName } from './OssBucketName';
import {
    OssBucketNameFromJSON,
    OssBucketNameFromJSONTyped,
    OssBucketNameToJSON,
} from './OssBucketName';

/**
 * 
 * @export
 * @interface OssOss
 */
export interface OssOss {
    /**
     * 
     * @type {number}
     * @memberof OssOss
     */
    id?: number;
    /**
     * 
     * @type {OssBucketName}
     * @memberof OssOss
     */
    bucketName?: OssBucketName;
    /**
     * 
     * @type {string}
     * @memberof OssOss
     */
    objectKey?: string;
    /**
     * 
     * @type {string}
     * @memberof OssOss
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof OssOss
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OssOss
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the OssOss interface.
 */
export function instanceOfOssOss(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OssOssFromJSON(json: any): OssOss {
    return OssOssFromJSONTyped(json, false);
}

export function OssOssFromJSONTyped(json: any, ignoreDiscriminator: boolean): OssOss {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'bucketName': !exists(json, 'bucketName') ? undefined : OssBucketNameFromJSON(json['bucketName']),
        'objectKey': !exists(json, 'objectKey') ? undefined : json['objectKey'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function OssOssToJSON(value?: OssOss | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'bucketName': OssBucketNameToJSON(value.bucketName),
        'objectKey': value.objectKey,
        'name': value.name,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

