/* tslint:disable */
/* eslint-disable */
/**
 * health/department.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DepartmentNewHepartment } from './DepartmentNewHepartment';
import {
    DepartmentNewHepartmentFromJSON,
    DepartmentNewHepartmentFromJSONTyped,
    DepartmentNewHepartmentToJSON,
} from './DepartmentNewHepartment';

/**
 * 
 * @export
 * @interface HealthdepartmentCreateRequest
 */
export interface HealthdepartmentCreateRequest {
    /**
     * 
     * @type {DepartmentNewHepartment}
     * @memberof HealthdepartmentCreateRequest
     */
    department?: DepartmentNewHepartment;
}

/**
 * Check if a given object implements the HealthdepartmentCreateRequest interface.
 */
export function instanceOfHealthdepartmentCreateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthdepartmentCreateRequestFromJSON(json: any): HealthdepartmentCreateRequest {
    return HealthdepartmentCreateRequestFromJSONTyped(json, false);
}

export function HealthdepartmentCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthdepartmentCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'department': !exists(json, 'department') ? undefined : DepartmentNewHepartmentFromJSON(json['department']),
    };
}

export function HealthdepartmentCreateRequestToJSON(value?: HealthdepartmentCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'department': DepartmentNewHepartmentToJSON(value.department),
    };
}

