/* tslint:disable */
/* eslint-disable */
/**
 * oauth/oauth.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OauthClient } from './OauthClient';
import {
    OauthClientFromJSON,
    OauthClientFromJSONTyped,
    OauthClientToJSON,
} from './OauthClient';

/**
 * 
 * @export
 * @interface OauthClientListResponse
 */
export interface OauthClientListResponse {
    /**
     * 
     * @type {Array<OauthClient>}
     * @memberof OauthClientListResponse
     */
    clients?: Array<OauthClient>;
}

/**
 * Check if a given object implements the OauthClientListResponse interface.
 */
export function instanceOfOauthClientListResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OauthClientListResponseFromJSON(json: any): OauthClientListResponse {
    return OauthClientListResponseFromJSONTyped(json, false);
}

export function OauthClientListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthClientListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'clients': !exists(json, 'clients') ? undefined : ((json['clients'] as Array<any>).map(OauthClientFromJSON)),
    };
}

export function OauthClientListResponseToJSON(value?: OauthClientListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'clients': value.clients === undefined ? undefined : ((value.clients as Array<any>).map(OauthClientToJSON)),
    };
}

