/* tslint:disable */
/* eslint-disable */
/**
 * lottery/template.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplateTemplateWithLottery } from './TemplateTemplateWithLottery';
import {
    TemplateTemplateWithLotteryFromJSON,
    TemplateTemplateWithLotteryFromJSONTyped,
    TemplateTemplateWithLotteryToJSON,
} from './TemplateTemplateWithLottery';

/**
 * 
 * @export
 * @interface LotterytemplateGetResponse
 */
export interface LotterytemplateGetResponse {
    /**
     * 
     * @type {TemplateTemplateWithLottery}
     * @memberof LotterytemplateGetResponse
     */
    template?: TemplateTemplateWithLottery;
}

/**
 * Check if a given object implements the LotterytemplateGetResponse interface.
 */
export function instanceOfLotterytemplateGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LotterytemplateGetResponseFromJSON(json: any): LotterytemplateGetResponse {
    return LotterytemplateGetResponseFromJSONTyped(json, false);
}

export function LotterytemplateGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LotterytemplateGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'template': !exists(json, 'template') ? undefined : TemplateTemplateWithLotteryFromJSON(json['template']),
    };
}

export function LotterytemplateGetResponseToJSON(value?: LotterytemplateGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'template': TemplateTemplateWithLotteryToJSON(value.template),
    };
}

