/* tslint:disable */
/* eslint-disable */
/**
 * lottery/template.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LotterytemplateFavorite
 */
export interface LotterytemplateFavorite {
    /**
     * 
     * @type {number}
     * @memberof LotterytemplateFavorite
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LotterytemplateFavorite
     */
    userId?: string;
    /**
     * 
     * @type {number}
     * @memberof LotterytemplateFavorite
     */
    lotteryId?: number;
}

/**
 * Check if a given object implements the LotterytemplateFavorite interface.
 */
export function instanceOfLotterytemplateFavorite(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LotterytemplateFavoriteFromJSON(json: any): LotterytemplateFavorite {
    return LotterytemplateFavoriteFromJSONTyped(json, false);
}

export function LotterytemplateFavoriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): LotterytemplateFavorite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'lotteryId': !exists(json, 'lotteryId') ? undefined : json['lotteryId'],
    };
}

export function LotterytemplateFavoriteToJSON(value?: LotterytemplateFavorite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'lotteryId': value.lotteryId,
    };
}

