/* tslint:disable */
/* eslint-disable */
/**
 * lottery/template.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LotteryItem
 */
export interface LotteryItem {
    /**
     * 
     * @type {number}
     * @memberof LotteryItem
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof LotteryItem
     */
    lotteryId?: number;
    /**
     * 
     * @type {string}
     * @memberof LotteryItem
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof LotteryItem
     */
    value?: number;
    /**
     * 
     * @type {Date}
     * @memberof LotteryItem
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof LotteryItem
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the LotteryItem interface.
 */
export function instanceOfLotteryItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LotteryItemFromJSON(json: any): LotteryItem {
    return LotteryItemFromJSONTyped(json, false);
}

export function LotteryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): LotteryItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'lotteryId': !exists(json, 'lotteryId') ? undefined : json['lotteryId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function LotteryItemToJSON(value?: LotteryItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'lotteryId': value.lotteryId,
        'name': value.name,
        'value': value.value,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

