/* tslint:disable */
/* eslint-disable */
/**
 * lottery/template.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TemplateNewTemplate } from './TemplateNewTemplate';
import {
    TemplateNewTemplateFromJSON,
    TemplateNewTemplateFromJSONTyped,
    TemplateNewTemplateToJSON,
} from './TemplateNewTemplate';

/**
 * 
 * @export
 * @interface TemplateServiceUpdateRequest
 */
export interface TemplateServiceUpdateRequest {
    /**
     * 
     * @type {TemplateNewTemplate}
     * @memberof TemplateServiceUpdateRequest
     */
    template?: TemplateNewTemplate;
}

/**
 * Check if a given object implements the TemplateServiceUpdateRequest interface.
 */
export function instanceOfTemplateServiceUpdateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TemplateServiceUpdateRequestFromJSON(json: any): TemplateServiceUpdateRequest {
    return TemplateServiceUpdateRequestFromJSONTyped(json, false);
}

export function TemplateServiceUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateServiceUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'template': !exists(json, 'template') ? undefined : TemplateNewTemplateFromJSON(json['template']),
    };
}

export function TemplateServiceUpdateRequestToJSON(value?: TemplateServiceUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'template': TemplateNewTemplateToJSON(value.template),
    };
}

