/* tslint:disable */
/* eslint-disable */
/**
 * user/user.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UseruserInfo } from './UseruserInfo';
import {
    UseruserInfoFromJSON,
    UseruserInfoFromJSONTyped,
    UseruserInfoToJSON,
} from './UseruserInfo';

/**
 * 
 * @export
 * @interface UserUpdateInfoResponse
 */
export interface UserUpdateInfoResponse {
    /**
     * 
     * @type {UseruserInfo}
     * @memberof UserUpdateInfoResponse
     */
    info?: UseruserInfo;
}

/**
 * Check if a given object implements the UserUpdateInfoResponse interface.
 */
export function instanceOfUserUpdateInfoResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserUpdateInfoResponseFromJSON(json: any): UserUpdateInfoResponse {
    return UserUpdateInfoResponseFromJSONTyped(json, false);
}

export function UserUpdateInfoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserUpdateInfoResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'info': !exists(json, 'info') ? undefined : UseruserInfoFromJSON(json['info']),
    };
}

export function UserUpdateInfoResponseToJSON(value?: UserUpdateInfoResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'info': UseruserInfoToJSON(value.info),
    };
}

