/* tslint:disable */
/* eslint-disable */
/**
 * user/user.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthToken } from './AuthToken';
import {
    AuthTokenFromJSON,
    AuthTokenFromJSONTyped,
    AuthTokenToJSON,
} from './AuthToken';
import type { UseruserUser } from './UseruserUser';
import {
    UseruserUserFromJSON,
    UseruserUserFromJSONTyped,
    UseruserUserToJSON,
} from './UseruserUser';

/**
 * 
 * @export
 * @interface UseruserRegisterResponse
 */
export interface UseruserRegisterResponse {
    /**
     * 
     * @type {UseruserUser}
     * @memberof UseruserRegisterResponse
     */
    user?: UseruserUser;
    /**
     * 
     * @type {AuthToken}
     * @memberof UseruserRegisterResponse
     */
    token?: AuthToken;
}

/**
 * Check if a given object implements the UseruserRegisterResponse interface.
 */
export function instanceOfUseruserRegisterResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UseruserRegisterResponseFromJSON(json: any): UseruserRegisterResponse {
    return UseruserRegisterResponseFromJSONTyped(json, false);
}

export function UseruserRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UseruserRegisterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UseruserUserFromJSON(json['user']),
        'token': !exists(json, 'token') ? undefined : AuthTokenFromJSON(json['token']),
    };
}

export function UseruserRegisterResponseToJSON(value?: UseruserRegisterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UseruserUserToJSON(value.user),
        'token': AuthTokenToJSON(value.token),
    };
}

