/* tslint:disable */
/* eslint-disable */
/**
 * wx/user.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserNewUser } from './UserNewUser';
import {
    UserNewUserFromJSON,
    UserNewUserFromJSONTyped,
    UserNewUserToJSON,
} from './UserNewUser';

/**
 * 
 * @export
 * @interface UserServiceUpdateRequest
 */
export interface UserServiceUpdateRequest {
    /**
     * 
     * @type {UserNewUser}
     * @memberof UserServiceUpdateRequest
     */
    wxUser?: UserNewUser;
}

/**
 * Check if a given object implements the UserServiceUpdateRequest interface.
 */
export function instanceOfUserServiceUpdateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserServiceUpdateRequestFromJSON(json: any): UserServiceUpdateRequest {
    return UserServiceUpdateRequestFromJSONTyped(json, false);
}

export function UserServiceUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserServiceUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'wxUser': !exists(json, 'wxUser') ? undefined : UserNewUserFromJSON(json['wxUser']),
    };
}

export function UserServiceUpdateRequestToJSON(value?: UserServiceUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'wxUser': UserNewUserToJSON(value.wxUser),
    };
}

