/* tslint:disable */
/* eslint-disable */
/**
 * user.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserUser } from './UserUser';
import {
    UserUserFromJSON,
    UserUserFromJSONTyped,
    UserUserToJSON,
} from './UserUser';

/**
 * 
 * @export
 * @interface UserCreateResponse
 */
export interface UserCreateResponse {
    /**
     * 
     * @type {UserUser}
     * @memberof UserCreateResponse
     */
    user?: UserUser;
}

/**
 * Check if a given object implements the UserCreateResponse interface.
 */
export function instanceOfUserCreateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserCreateResponseFromJSON(json: any): UserCreateResponse {
    return UserCreateResponseFromJSONTyped(json, false);
}

export function UserCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UserUserFromJSON(json['user']),
    };
}

export function UserCreateResponseToJSON(value?: UserCreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserUserToJSON(value.user),
    };
}

