/* tslint:disable */
/* eslint-disable */
/**
 * record.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface ProtobufAny
 */
export interface ProtobufAny {
    [key: string]: object | any;

    /**
     * 
     * @type {string}
     * @memberof ProtobufAny
     */
    '@type'?: string;
}
/**
 * 
 * @export
 * @interface RecordCreateRequest
 */
export interface RecordCreateRequest {
    /**
     * 
     * @type {RecordNewRecord}
     * @memberof RecordCreateRequest
     */
    'record'?: RecordNewRecord;
}
/**
 * 
 * @export
 * @interface RecordCreateResponse
 */
export interface RecordCreateResponse {
    /**
     * 
     * @type {RecordRecord}
     * @memberof RecordCreateResponse
     */
    'record'?: RecordRecord;
}
/**
 * 
 * @export
 * @interface RecordGetResponse
 */
export interface RecordGetResponse {
    /**
     * 
     * @type {RecordRecord}
     * @memberof RecordGetResponse
     */
    'record'?: RecordRecord;
}
/**
 * 
 * @export
 * @interface RecordListResponse
 */
export interface RecordListResponse {
    /**
     * 
     * @type {Array<RecordRecord>}
     * @memberof RecordListResponse
     */
    'records'?: Array<RecordRecord>;
}
/**
 * 
 * @export
 * @interface RecordNewRecord
 */
export interface RecordNewRecord {
    /**
     * 
     * @type {number}
     * @memberof RecordNewRecord
     */
    'lotteryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof RecordNewRecord
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecordNewRecord
     */
    'value'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecordNewRecord
     */
    'remarks'?: Array<string>;
}
/**
 * 
 * @export
 * @interface RecordRecord
 */
export interface RecordRecord {
    /**
     * 
     * @type {number}
     * @memberof RecordRecord
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof RecordRecord
     */
    'lotteryId'?: number;
    /**
     * 
     * @type {string}
     * @memberof RecordRecord
     */
    'userId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecordRecord
     */
    'value'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecordRecord
     */
    'remarks'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RecordRecord
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof RecordRecord
     */
    'updatedAt'?: string;
}
/**
 * 
 * @export
 * @interface RecordServiceUpdateRequest
 */
export interface RecordServiceUpdateRequest {
    /**
     * 
     * @type {RecordNewRecord}
     * @memberof RecordServiceUpdateRequest
     */
    'record'?: RecordNewRecord;
}
/**
 * 
 * @export
 * @interface RecordUpdateResponse
 */
export interface RecordUpdateResponse {
    /**
     * 
     * @type {RecordRecord}
     * @memberof RecordUpdateResponse
     */
    'record'?: RecordRecord;
}
/**
 * 
 * @export
 * @interface RpcStatus
 */
export interface RpcStatus {
    /**
     * 
     * @type {number}
     * @memberof RpcStatus
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof RpcStatus
     */
    'message'?: string;
    /**
     * 
     * @type {Array<ProtobufAny>}
     * @memberof RpcStatus
     */
    'details'?: Array<ProtobufAny>;
}

/**
 * RecordServiceApi - axios parameter creator
 * @export
 */
export const RecordServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {RecordCreateRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceCreate: async (body: RecordCreateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('recordServiceCreate', 'body', body)
            const localVarPath = `/record.RecordService/records`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recordServiceDelete', 'id', id)
            const localVarPath = `/record.RecordService/records/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recordServiceGet', 'id', id)
            const localVarPath = `/record.RecordService/records/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} [recordId] id
         * @param {number} [recordLotteryId] id
         * @param {string} [recordUserId] id
         * @param {string} [recordValue] lottery image
         * @param {Array<string>} [recordRemarks] 
         * @param {string} [recordCreatedAt] 
         * @param {string} [recordUpdatedAt] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceList: async (recordId?: number, recordLotteryId?: number, recordUserId?: string, recordValue?: string, recordRemarks?: Array<string>, recordCreatedAt?: string, recordUpdatedAt?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/record.RecordService/records`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (recordId !== undefined) {
                localVarQueryParameter['record.id'] = recordId;
            }

            if (recordLotteryId !== undefined) {
                localVarQueryParameter['record.lotteryId'] = recordLotteryId;
            }

            if (recordUserId !== undefined) {
                localVarQueryParameter['record.userId'] = recordUserId;
            }

            if (recordValue !== undefined) {
                localVarQueryParameter['record.value'] = recordValue;
            }

            if (recordRemarks) {
                localVarQueryParameter['record.remarks'] = recordRemarks;
            }

            if (recordCreatedAt !== undefined) {
                localVarQueryParameter['record.createdAt'] = (recordCreatedAt as any instanceof Date) ?
                    (recordCreatedAt as any).toISOString() :
                    recordCreatedAt;
            }

            if (recordUpdatedAt !== undefined) {
                localVarQueryParameter['record.updatedAt'] = (recordUpdatedAt as any instanceof Date) ?
                    (recordUpdatedAt as any).toISOString() :
                    recordUpdatedAt;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {RecordServiceUpdateRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceUpdate: async (id: number, body: RecordServiceUpdateRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('recordServiceUpdate', 'id', id)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('recordServiceUpdate', 'body', body)
            const localVarPath = `/record.RecordService/records/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecordServiceApi - functional programming interface
 * @export
 */
export const RecordServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecordServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {RecordCreateRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordServiceCreate(body: RecordCreateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecordCreateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordServiceCreate(body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordServiceDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordServiceDelete(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordServiceGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecordGetResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordServiceGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} [recordId] id
         * @param {number} [recordLotteryId] id
         * @param {string} [recordUserId] id
         * @param {string} [recordValue] lottery image
         * @param {Array<string>} [recordRemarks] 
         * @param {string} [recordCreatedAt] 
         * @param {string} [recordUpdatedAt] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordServiceList(recordId?: number, recordLotteryId?: number, recordUserId?: string, recordValue?: string, recordRemarks?: Array<string>, recordCreatedAt?: string, recordUpdatedAt?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecordListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordServiceList(recordId, recordLotteryId, recordUserId, recordValue, recordRemarks, recordCreatedAt, recordUpdatedAt, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {number} id 
         * @param {RecordServiceUpdateRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recordServiceUpdate(id: number, body: RecordServiceUpdateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RecordUpdateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recordServiceUpdate(id, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RecordServiceApi - factory interface
 * @export
 */
export const RecordServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecordServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {RecordCreateRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceCreate(body: RecordCreateRequest, options?: any): AxiosPromise<RecordCreateResponse> {
            return localVarFp.recordServiceCreate(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceDelete(id: number, options?: any): AxiosPromise<object> {
            return localVarFp.recordServiceDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceGet(id: number, options?: any): AxiosPromise<RecordGetResponse> {
            return localVarFp.recordServiceGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} [recordId] id
         * @param {number} [recordLotteryId] id
         * @param {string} [recordUserId] id
         * @param {string} [recordValue] lottery image
         * @param {Array<string>} [recordRemarks] 
         * @param {string} [recordCreatedAt] 
         * @param {string} [recordUpdatedAt] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceList(recordId?: number, recordLotteryId?: number, recordUserId?: string, recordValue?: string, recordRemarks?: Array<string>, recordCreatedAt?: string, recordUpdatedAt?: string, options?: any): AxiosPromise<RecordListResponse> {
            return localVarFp.recordServiceList(recordId, recordLotteryId, recordUserId, recordValue, recordRemarks, recordCreatedAt, recordUpdatedAt, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {RecordServiceUpdateRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recordServiceUpdate(id: number, body: RecordServiceUpdateRequest, options?: any): AxiosPromise<RecordUpdateResponse> {
            return localVarFp.recordServiceUpdate(id, body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecordServiceApi - object-oriented interface
 * @export
 * @class RecordServiceApi
 * @extends {BaseAPI}
 */
export class RecordServiceApi extends BaseAPI {
    /**
     * 
     * @param {RecordCreateRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecordServiceApi
     */
    public recordServiceCreate(body: RecordCreateRequest, options?: AxiosRequestConfig) {
        return RecordServiceApiFp(this.configuration).recordServiceCreate(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecordServiceApi
     */
    public recordServiceDelete(id: number, options?: AxiosRequestConfig) {
        return RecordServiceApiFp(this.configuration).recordServiceDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecordServiceApi
     */
    public recordServiceGet(id: number, options?: AxiosRequestConfig) {
        return RecordServiceApiFp(this.configuration).recordServiceGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} [recordId] id
     * @param {number} [recordLotteryId] id
     * @param {string} [recordUserId] id
     * @param {string} [recordValue] lottery image
     * @param {Array<string>} [recordRemarks] 
     * @param {string} [recordCreatedAt] 
     * @param {string} [recordUpdatedAt] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecordServiceApi
     */
    public recordServiceList(recordId?: number, recordLotteryId?: number, recordUserId?: string, recordValue?: string, recordRemarks?: Array<string>, recordCreatedAt?: string, recordUpdatedAt?: string, options?: AxiosRequestConfig) {
        return RecordServiceApiFp(this.configuration).recordServiceList(recordId, recordLotteryId, recordUserId, recordValue, recordRemarks, recordCreatedAt, recordUpdatedAt, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {number} id 
     * @param {RecordServiceUpdateRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecordServiceApi
     */
    public recordServiceUpdate(id: number, body: RecordServiceUpdateRequest, options?: AxiosRequestConfig) {
        return RecordServiceApiFp(this.configuration).recordServiceUpdate(id, body, options).then((request) => request(this.axios, this.basePath));
    }
}


