/* tslint:disable */
/* eslint-disable */
/**
 * lottery/record.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecordNewRecordRemark
 */
export interface RecordNewRecordRemark {
    /**
     * 
     * @type {number}
     * @memberof RecordNewRecordRemark
     */
    recordId?: number;
    /**
     * 
     * @type {number}
     * @memberof RecordNewRecordRemark
     */
    remarkId?: number;
    /**
     * 
     * @type {string}
     * @memberof RecordNewRecordRemark
     */
    value?: string;
}

/**
 * Check if a given object implements the RecordNewRecordRemark interface.
 */
export function instanceOfRecordNewRecordRemark(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RecordNewRecordRemarkFromJSON(json: any): RecordNewRecordRemark {
    return RecordNewRecordRemarkFromJSONTyped(json, false);
}

export function RecordNewRecordRemarkFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecordNewRecordRemark {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'recordId': !exists(json, 'recordId') ? undefined : json['recordId'],
        'remarkId': !exists(json, 'remarkId') ? undefined : json['remarkId'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function RecordNewRecordRemarkToJSON(value?: RecordNewRecordRemark | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'recordId': value.recordId,
        'remarkId': value.remarkId,
        'value': value.value,
    };
}

