/* tslint:disable */
/* eslint-disable */
/**
 * wx/user.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthoauthUser
 */
export interface OauthoauthUser {
    /**
     * 
     * @type {string}
     * @memberof OauthoauthUser
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof OauthoauthUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OauthoauthUser
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the OauthoauthUser interface.
 */
export function instanceOfOauthoauthUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OauthoauthUserFromJSON(json: any): OauthoauthUser {
    return OauthoauthUserFromJSONTyped(json, false);
}

export function OauthoauthUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthoauthUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function OauthoauthUserToJSON(value?: OauthoauthUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

