/* tslint:disable */
/* eslint-disable */
/**
 * wx/user.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthToken } from './AuthToken';
import {
    AuthTokenFromJSON,
    AuthTokenFromJSONTyped,
    AuthTokenToJSON,
} from './AuthToken';
import type { AuthauthUser } from './AuthauthUser';
import {
    AuthauthUserFromJSON,
    AuthauthUserFromJSONTyped,
    AuthauthUserToJSON,
} from './AuthauthUser';

/**
 * 
 * @export
 * @interface WxuserLoginResponse
 */
export interface WxuserLoginResponse {
    /**
     * 
     * @type {AuthToken}
     * @memberof WxuserLoginResponse
     */
    token?: AuthToken;
    /**
     * 
     * @type {AuthauthUser}
     * @memberof WxuserLoginResponse
     */
    user?: AuthauthUser;
}

/**
 * Check if a given object implements the WxuserLoginResponse interface.
 */
export function instanceOfWxuserLoginResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WxuserLoginResponseFromJSON(json: any): WxuserLoginResponse {
    return WxuserLoginResponseFromJSONTyped(json, false);
}

export function WxuserLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WxuserLoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : AuthTokenFromJSON(json['token']),
        'user': !exists(json, 'user') ? undefined : AuthauthUserFromJSON(json['user']),
    };
}

export function WxuserLoginResponseToJSON(value?: WxuserLoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': AuthTokenToJSON(value.token),
        'user': AuthauthUserToJSON(value.user),
    };
}

