/* tslint:disable */
/* eslint-disable */
/**
 * wx/user.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WxuserUser
 */
export interface WxuserUser {
    /**
     * 
     * @type {string}
     * @memberof WxuserUser
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WxuserUser
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof WxuserUser
     */
    openid?: string;
    /**
     * 
     * @type {string}
     * @memberof WxuserUser
     */
    unionid?: string;
    /**
     * 
     * @type {string}
     * @memberof WxuserUser
     */
    sessionKey?: string;
    /**
     * 
     * @type {string}
     * @memberof WxuserUser
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof WxuserUser
     */
    avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof WxuserUser
     */
    mobile?: string;
    /**
     * 
     * @type {Date}
     * @memberof WxuserUser
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WxuserUser
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the WxuserUser interface.
 */
export function instanceOfWxuserUser(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WxuserUserFromJSON(json: any): WxuserUser {
    return WxuserUserFromJSONTyped(json, false);
}

export function WxuserUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): WxuserUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'openid': !exists(json, 'openid') ? undefined : json['openid'],
        'unionid': !exists(json, 'unionid') ? undefined : json['unionid'],
        'sessionKey': !exists(json, 'sessionKey') ? undefined : json['sessionKey'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'avatar': !exists(json, 'avatar') ? undefined : json['avatar'],
        'mobile': !exists(json, 'mobile') ? undefined : json['mobile'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function WxuserUserToJSON(value?: WxuserUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'openid': value.openid,
        'unionid': value.unionid,
        'sessionKey': value.sessionKey,
        'name': value.name,
        'avatar': value.avatar,
        'mobile': value.mobile,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

