/* tslint:disable */
/* eslint-disable */
/**
 * lottery/favorite.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LotteryfavoriteNewFavorite
 */
export interface LotteryfavoriteNewFavorite {
    /**
     * 
     * @type {string}
     * @memberof LotteryfavoriteNewFavorite
     */
    userId?: string;
    /**
     * 
     * @type {number}
     * @memberof LotteryfavoriteNewFavorite
     */
    lotteryId?: number;
}

/**
 * Check if a given object implements the LotteryfavoriteNewFavorite interface.
 */
export function instanceOfLotteryfavoriteNewFavorite(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LotteryfavoriteNewFavoriteFromJSON(json: any): LotteryfavoriteNewFavorite {
    return LotteryfavoriteNewFavoriteFromJSONTyped(json, false);
}

export function LotteryfavoriteNewFavoriteFromJSONTyped(json: any, ignoreDiscriminator: boolean): LotteryfavoriteNewFavorite {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'lotteryId': !exists(json, 'lotteryId') ? undefined : json['lotteryId'],
    };
}

export function LotteryfavoriteNewFavoriteToJSON(value?: LotteryfavoriteNewFavorite | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'lotteryId': value.lotteryId,
    };
}

