/* tslint:disable */
/* eslint-disable */
/**
 * health/patient.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HospitalHospital } from './HospitalHospital';
import {
    HospitalHospitalFromJSON,
    HospitalHospitalFromJSONTyped,
    HospitalHospitalToJSON,
} from './HospitalHospital';
import type { PatientPatient } from './PatientPatient';
import {
    PatientPatientFromJSON,
    PatientPatientFromJSONTyped,
    PatientPatientToJSON,
} from './PatientPatient';

/**
 * 
 * @export
 * @interface HealthpatientGetResponse
 */
export interface HealthpatientGetResponse {
    /**
     * 
     * @type {PatientPatient}
     * @memberof HealthpatientGetResponse
     */
    patient?: PatientPatient;
    /**
     * 
     * @type {HospitalHospital}
     * @memberof HealthpatientGetResponse
     */
    hospital?: HospitalHospital;
}

/**
 * Check if a given object implements the HealthpatientGetResponse interface.
 */
export function instanceOfHealthpatientGetResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthpatientGetResponseFromJSON(json: any): HealthpatientGetResponse {
    return HealthpatientGetResponseFromJSONTyped(json, false);
}

export function HealthpatientGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthpatientGetResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patient': !exists(json, 'patient') ? undefined : PatientPatientFromJSON(json['patient']),
        'hospital': !exists(json, 'hospital') ? undefined : HospitalHospitalFromJSON(json['hospital']),
    };
}

export function HealthpatientGetResponseToJSON(value?: HealthpatientGetResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient': PatientPatientToJSON(value.patient),
        'hospital': HospitalHospitalToJSON(value.hospital),
    };
}

