/* tslint:disable */
/* eslint-disable */
/**
 * health/patient.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PatientPatient } from './PatientPatient';
import {
    PatientPatientFromJSON,
    PatientPatientFromJSONTyped,
    PatientPatientToJSON,
} from './PatientPatient';

/**
 * 
 * @export
 * @interface HealthpatientCreateResponse
 */
export interface HealthpatientCreateResponse {
    /**
     * 
     * @type {PatientPatient}
     * @memberof HealthpatientCreateResponse
     */
    patient?: PatientPatient;
}

/**
 * Check if a given object implements the HealthpatientCreateResponse interface.
 */
export function instanceOfHealthpatientCreateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthpatientCreateResponseFromJSON(json: any): HealthpatientCreateResponse {
    return HealthpatientCreateResponseFromJSONTyped(json, false);
}

export function HealthpatientCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthpatientCreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patient': !exists(json, 'patient') ? undefined : PatientPatientFromJSON(json['patient']),
    };
}

export function HealthpatientCreateResponseToJSON(value?: HealthpatientCreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient': PatientPatientToJSON(value.patient),
    };
}

