/* tslint:disable */
/* eslint-disable */
/**
 * health/patient.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PatientNewPatient } from './PatientNewPatient';
import {
    PatientNewPatientFromJSON,
    PatientNewPatientFromJSONTyped,
    PatientNewPatientToJSON,
} from './PatientNewPatient';

/**
 * 
 * @export
 * @interface HealthpatientCreateRequest
 */
export interface HealthpatientCreateRequest {
    /**
     * 
     * @type {PatientNewPatient}
     * @memberof HealthpatientCreateRequest
     */
    patient?: PatientNewPatient;
}

/**
 * Check if a given object implements the HealthpatientCreateRequest interface.
 */
export function instanceOfHealthpatientCreateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthpatientCreateRequestFromJSON(json: any): HealthpatientCreateRequest {
    return HealthpatientCreateRequestFromJSONTyped(json, false);
}

export function HealthpatientCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthpatientCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'patient': !exists(json, 'patient') ? undefined : PatientNewPatientFromJSON(json['patient']),
    };
}

export function HealthpatientCreateRequestToJSON(value?: HealthpatientCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'patient': PatientNewPatientToJSON(value.patient),
    };
}

