/* tslint:disable */
/* eslint-disable */
/**
 * auth/auth.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AuthToken } from './AuthToken';
import {
    AuthTokenFromJSON,
    AuthTokenFromJSONTyped,
    AuthTokenToJSON,
} from './AuthToken';
import type { AuthauthUser } from './AuthauthUser';
import {
    AuthauthUserFromJSON,
    AuthauthUserFromJSONTyped,
    AuthauthUserToJSON,
} from './AuthauthUser';

/**
 * 
 * @export
 * @interface AuthRegisterResponse
 */
export interface AuthRegisterResponse {
    /**
     * 
     * @type {AuthauthUser}
     * @memberof AuthRegisterResponse
     */
    user?: AuthauthUser;
    /**
     * 
     * @type {AuthToken}
     * @memberof AuthRegisterResponse
     */
    token?: AuthToken;
}

/**
 * Check if a given object implements the AuthRegisterResponse interface.
 */
export function instanceOfAuthRegisterResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthRegisterResponseFromJSON(json: any): AuthRegisterResponse {
    return AuthRegisterResponseFromJSONTyped(json, false);
}

export function AuthRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : AuthauthUserFromJSON(json['user']),
        'token': !exists(json, 'token') ? undefined : AuthTokenFromJSON(json['token']),
    };
}

export function AuthRegisterResponseToJSON(value?: AuthRegisterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': AuthauthUserToJSON(value.user),
        'token': AuthTokenToJSON(value.token),
    };
}

