/* tslint:disable */
/* eslint-disable */
/**
 * auth/auth.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthPattern
 */
export interface AuthPattern {
    /**
     * 
     * @type {string}
     * @memberof AuthPattern
     */
    equal?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthPattern
     */
    prefix?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthPattern
     */
    regex?: string;
}

/**
 * Check if a given object implements the AuthPattern interface.
 */
export function instanceOfAuthPattern(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthPatternFromJSON(json: any): AuthPattern {
    return AuthPatternFromJSONTyped(json, false);
}

export function AuthPatternFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthPattern {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'equal': !exists(json, 'equal') ? undefined : json['equal'],
        'prefix': !exists(json, 'prefix') ? undefined : json['prefix'],
        'regex': !exists(json, 'regex') ? undefined : json['regex'],
    };
}

export function AuthPatternToJSON(value?: AuthPattern | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'equal': value.equal,
        'prefix': value.prefix,
        'regex': value.regex,
    };
}

