/* tslint:disable */
/* eslint-disable */
/**
 * health/nurse.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NurseNurse } from './NurseNurse';
import {
    NurseNurseFromJSON,
    NurseNurseFromJSONTyped,
    NurseNurseToJSON,
} from './NurseNurse';

/**
 * 
 * @export
 * @interface HealthnurseCreateResponse
 */
export interface HealthnurseCreateResponse {
    /**
     * 
     * @type {NurseNurse}
     * @memberof HealthnurseCreateResponse
     */
    nurse?: NurseNurse;
}

/**
 * Check if a given object implements the HealthnurseCreateResponse interface.
 */
export function instanceOfHealthnurseCreateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthnurseCreateResponseFromJSON(json: any): HealthnurseCreateResponse {
    return HealthnurseCreateResponseFromJSONTyped(json, false);
}

export function HealthnurseCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthnurseCreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nurse': !exists(json, 'nurse') ? undefined : NurseNurseFromJSON(json['nurse']),
    };
}

export function HealthnurseCreateResponseToJSON(value?: HealthnurseCreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nurse': NurseNurseToJSON(value.nurse),
    };
}

