/* tslint:disable */
/* eslint-disable */
/**
 * health/nurse.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { NurseNewNurse } from './NurseNewNurse';
import {
    NurseNewNurseFromJSON,
    NurseNewNurseFromJSONTyped,
    NurseNewNurseToJSON,
} from './NurseNewNurse';

/**
 * 
 * @export
 * @interface NurseServiceUpdateRequest
 */
export interface NurseServiceUpdateRequest {
    /**
     * 
     * @type {NurseNewNurse}
     * @memberof NurseServiceUpdateRequest
     */
    nurse?: NurseNewNurse;
}

/**
 * Check if a given object implements the NurseServiceUpdateRequest interface.
 */
export function instanceOfNurseServiceUpdateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NurseServiceUpdateRequestFromJSON(json: any): NurseServiceUpdateRequest {
    return NurseServiceUpdateRequestFromJSONTyped(json, false);
}

export function NurseServiceUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NurseServiceUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nurse': !exists(json, 'nurse') ? undefined : NurseNewNurseFromJSON(json['nurse']),
    };
}

export function NurseServiceUpdateRequestToJSON(value?: NurseServiceUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nurse': NurseNewNurseToJSON(value.nurse),
    };
}

