/* tslint:disable */
/* eslint-disable */
/**
 * user/user.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthToken,
  RpcStatus,
  UserLoginMobileRequest,
  UserLoginWeixinRequest,
  UserRegisterMobileRequest,
} from '../models';
import {
    AuthTokenFromJSON,
    AuthTokenToJSON,
    RpcStatusFromJSON,
    RpcStatusToJSON,
    UserLoginMobileRequestFromJSON,
    UserLoginMobileRequestToJSON,
    UserLoginWeixinRequestFromJSON,
    UserLoginWeixinRequestToJSON,
    UserRegisterMobileRequestFromJSON,
    UserRegisterMobileRequestToJSON,
} from '../models';

export interface UserServiceLoginMobileRequest {
    body: UserLoginMobileRequest;
}

export interface UserServiceLoginWeixinRequest {
    body: UserLoginWeixinRequest;
}

export interface UserServiceRegisterMobileRequest {
    body: UserRegisterMobileRequest;
}

/**
 * 
 */
export class UserServiceApi extends runtime.BaseAPI {

    /**
     */
    async userServiceLoginMobileRaw(requestParameters: UserServiceLoginMobileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthToken>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling userServiceLoginMobile.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user.user.UserService/loginMobile`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserLoginMobileRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthTokenFromJSON(jsonValue));
    }

    /**
     */
    async userServiceLoginMobile(requestParameters: UserServiceLoginMobileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthToken> {
        const response = await this.userServiceLoginMobileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userServiceLoginWeixinRaw(requestParameters: UserServiceLoginWeixinRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthToken>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling userServiceLoginWeixin.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user.user.UserService/loginWeixin`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserLoginWeixinRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthTokenFromJSON(jsonValue));
    }

    /**
     */
    async userServiceLoginWeixin(requestParameters: UserServiceLoginWeixinRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthToken> {
        const response = await this.userServiceLoginWeixinRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async userServiceRegisterMobileRaw(requestParameters: UserServiceRegisterMobileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthToken>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling userServiceRegisterMobile.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/user.user.UserService/registerMobile`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserRegisterMobileRequestToJSON(requestParameters.body),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthTokenFromJSON(jsonValue));
    }

    /**
     */
    async userServiceRegisterMobile(requestParameters: UserServiceRegisterMobileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthToken> {
        const response = await this.userServiceRegisterMobileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
