/* tslint:disable */
/* eslint-disable */
/**
 * lottery.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LotteryNewLottery } from './LotteryNewLottery';
import {
    LotteryNewLotteryFromJSON,
    LotteryNewLotteryFromJSONTyped,
    LotteryNewLotteryToJSON,
} from './LotteryNewLottery';

/**
 * 
 * @export
 * @interface LotteryCreateRequest
 */
export interface LotteryCreateRequest {
    /**
     * 
     * @type {LotteryNewLottery}
     * @memberof LotteryCreateRequest
     */
    lottery?: LotteryNewLottery;
}

/**
 * Check if a given object implements the LotteryCreateRequest interface.
 */
export function instanceOfLotteryCreateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LotteryCreateRequestFromJSON(json: any): LotteryCreateRequest {
    return LotteryCreateRequestFromJSONTyped(json, false);
}

export function LotteryCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LotteryCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lottery': !exists(json, 'lottery') ? undefined : LotteryNewLotteryFromJSON(json['lottery']),
    };
}

export function LotteryCreateRequestToJSON(value?: LotteryCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lottery': LotteryNewLotteryToJSON(value.lottery),
    };
}

