/* tslint:disable */
/* eslint-disable */
/**
 * lottery.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LotteryLottery } from './LotteryLottery';
import {
    LotteryLotteryFromJSON,
    LotteryLotteryFromJSONTyped,
    LotteryLotteryToJSON,
} from './LotteryLottery';

/**
 * 
 * @export
 * @interface LotteryUpdateResponse
 */
export interface LotteryUpdateResponse {
    /**
     * 
     * @type {LotteryLottery}
     * @memberof LotteryUpdateResponse
     */
    lottery?: LotteryLottery;
}

/**
 * Check if a given object implements the LotteryUpdateResponse interface.
 */
export function instanceOfLotteryUpdateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LotteryUpdateResponseFromJSON(json: any): LotteryUpdateResponse {
    return LotteryUpdateResponseFromJSONTyped(json, false);
}

export function LotteryUpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LotteryUpdateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lottery': !exists(json, 'lottery') ? undefined : LotteryLotteryFromJSON(json['lottery']),
    };
}

export function LotteryUpdateResponseToJSON(value?: LotteryUpdateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lottery': LotteryLotteryToJSON(value.lottery),
    };
}

