/* tslint:disable */
/* eslint-disable */
/**
 * health/hospital.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HospitalHospital } from './HospitalHospital';
import {
    HospitalHospitalFromJSON,
    HospitalHospitalFromJSONTyped,
    HospitalHospitalToJSON,
} from './HospitalHospital';

/**
 * 
 * @export
 * @interface HealthhospitalCreateResponse
 */
export interface HealthhospitalCreateResponse {
    /**
     * 
     * @type {HospitalHospital}
     * @memberof HealthhospitalCreateResponse
     */
    hospital?: HospitalHospital;
}

/**
 * Check if a given object implements the HealthhospitalCreateResponse interface.
 */
export function instanceOfHealthhospitalCreateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthhospitalCreateResponseFromJSON(json: any): HealthhospitalCreateResponse {
    return HealthhospitalCreateResponseFromJSONTyped(json, false);
}

export function HealthhospitalCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthhospitalCreateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hospital': !exists(json, 'hospital') ? undefined : HospitalHospitalFromJSON(json['hospital']),
    };
}

export function HealthhospitalCreateResponseToJSON(value?: HealthhospitalCreateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hospital': HospitalHospitalToJSON(value.hospital),
    };
}

