/* tslint:disable */
/* eslint-disable */
/**
 * health/hospital.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { HospitalNewHospital } from './HospitalNewHospital';
import {
    HospitalNewHospitalFromJSON,
    HospitalNewHospitalFromJSONTyped,
    HospitalNewHospitalToJSON,
} from './HospitalNewHospital';

/**
 * 
 * @export
 * @interface HealthhospitalCreateRequest
 */
export interface HealthhospitalCreateRequest {
    /**
     * 
     * @type {HospitalNewHospital}
     * @memberof HealthhospitalCreateRequest
     */
    hospital?: HospitalNewHospital;
}

/**
 * Check if a given object implements the HealthhospitalCreateRequest interface.
 */
export function instanceOfHealthhospitalCreateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthhospitalCreateRequestFromJSON(json: any): HealthhospitalCreateRequest {
    return HealthhospitalCreateRequestFromJSONTyped(json, false);
}

export function HealthhospitalCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthhospitalCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hospital': !exists(json, 'hospital') ? undefined : HospitalNewHospitalFromJSON(json['hospital']),
    };
}

export function HealthhospitalCreateRequestToJSON(value?: HealthhospitalCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hospital': HospitalNewHospitalToJSON(value.hospital),
    };
}

